name: AI Log Analyzer CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install pandas numpy scikit-learn nltk spacy flask streamlit

    - name: Run AI Log Analyzer
      run: |
        python log_analyzer.py